insert into vacuna (id, descripcion_enfermedad, nombre) values (1, 'Unspecified injury of left pulmonary blood vessels', 'Fransisco Wareing');
insert into vacuna (id, descripcion_enfermedad, nombre) values (2, 'Displ oblique fx shaft of r rad, 7thH', 'Babs Saurin');
insert into vacuna (id, descripcion_enfermedad, nombre) values (3, 'Unspecified open wound, right knee, subsequent encounter', 'Tawsha Crampsey');
insert into vacuna (id, descripcion_enfermedad, nombre) values (4, 'Snsrnrl hear loss, uni, with restricted hear cntra side', 'Amberly Mohammed');
insert into vacuna (id, descripcion_enfermedad, nombre) values (5, 'Nondisplaced fracture of greater tuberosity of right humerus', 'Rey Edmeads');
insert into vacuna (id, descripcion_enfermedad, nombre) values (6, 'Cocaine use, unspecified with intoxication delirium', 'Jeanette Gaine of England');
insert into vacuna (id, descripcion_enfermedad, nombre) values (7, 'Corrosion of first deg mult sites of left wrs/hnd, subs', 'Yelena Doberer');
insert into vacuna (id, descripcion_enfermedad, nombre) values (8, 'Path fx in neopltc disease, r shldr, subs for fx w malunion', 'Erhart Benoit');
insert into vacuna (id, descripcion_enfermedad, nombre) values (9, 'Other hypertrophic osteoarthropathy, left lower leg', 'Lela Hills');
insert into vacuna (id, descripcion_enfermedad, nombre) values (10, 'Corrosions of other internal organs, initial encounter', 'Meredith Tredger');
insert into vacuna (id, descripcion_enfermedad, nombre) values (11, 'Other diseases of pancreas', 'Datha Saing');
insert into vacuna (id, descripcion_enfermedad, nombre) values (12, 'Nondisp commnt fx shaft of unsp femr, 7thJ', 'Zondra Robart');
insert into vacuna (id, descripcion_enfermedad, nombre) values (13, 'Breakdown (mechanical) of artificial heart', 'Tybie Robel');
insert into vacuna (id, descripcion_enfermedad, nombre) values (14, 'Disp fx of shaft of third MC bone, right hand, sequela', 'Norby Antos');
insert into vacuna (id, descripcion_enfermedad, nombre) values (15, 'Contus/lac/hem brnst w LOC w dth d/t oth cause bf consc,init', 'Norrie Lissaman');
insert into vacuna (id, descripcion_enfermedad, nombre) values (16, 'Oth comp specific to multiple gest, second trimester, oth', 'Nahum Bodell');
insert into vacuna (id, descripcion_enfermedad, nombre) values (17, 'Other fracture of T9-T10 vertebra, sequela', 'Kylila Geraudy');
insert into vacuna (id, descripcion_enfermedad, nombre) values (18, 'Primary angle closure without glaucoma damage, bilateral', 'Coretta Ager');
insert into vacuna (id, descripcion_enfermedad, nombre) values (19, 'Displaced fracture of neck of other metacarpal bone', 'Sollie Stanbro');
insert into vacuna (id, descripcion_enfermedad, nombre) values (20, 'Excessive weight gain in pregnancy, first trimester', 'Melisandra Basler');
insert into vacuna (id, descripcion_enfermedad, nombre) values (21, 'Subluxation of tarsometatarsal joint of left foot, init', 'Bern Benson');
insert into vacuna (id, descripcion_enfermedad, nombre) values (22, 'Unspecified physeal fracture of right calcaneus', 'Prudi Joseland');
insert into vacuna (id, descripcion_enfermedad, nombre) values (23, 'Laceration of flexor musc/fasc/tend r rng fngr at wrs/hnd lv', 'Willdon Hearthfield');
insert into vacuna (id, descripcion_enfermedad, nombre) values (24, 'Other diseases of anus and rectum', 'Jasmina Keam');
insert into vacuna (id, descripcion_enfermedad, nombre) values (25, 'Oth osteopor w crnt path fx, unsp site, 7thG', 'Elwira Dearle');
insert into vacuna (id, descripcion_enfermedad, nombre) values (26, 'Lichen ruber moniliformis', 'Karry O''Connolly');
insert into vacuna (id, descripcion_enfermedad, nombre) values (27, 'Lacerat intrinsic msl/tnd at ank/ft level, right foot, subs', 'Cathy Frank');
insert into vacuna (id, descripcion_enfermedad, nombre) values (28, 'External constriction of upper arm', 'Buck Oneil');
insert into vacuna (id, descripcion_enfermedad, nombre) values (29, 'Frostbite with tissue necrosis of left hand', 'Stu Mathys');
insert into vacuna (id, descripcion_enfermedad, nombre) values (30, 'Inj flexor musc/fasc/tend left ring finger at wrs/hnd lv', 'Jordan Worral');
insert into vacuna (id, descripcion_enfermedad, nombre) values (31, 'External constriction, right thigh, subsequent encounter', 'Giuditta Gerholz');
insert into vacuna (id, descripcion_enfermedad, nombre) values (32, 'Nondisp fx of post column of r acetab, 7thG', 'Lorry Mea');
insert into vacuna (id, descripcion_enfermedad, nombre) values (33, 'Burn due to other powered watercraft on fire, subs encntr', 'Lucila Vynoll');
insert into vacuna (id, descripcion_enfermedad, nombre) values (34, 'Torus fracture of upper end of fibula', 'Eduard Escoffrey');
insert into vacuna (id, descripcion_enfermedad, nombre) values (35, 'Poisn by oth antacids and anti-gstrc-sec drugs, asslt, sqla', 'Tori Saice');
insert into vacuna (id, descripcion_enfermedad, nombre) values (36, 'Malignant neoplasm of unsp part of unsp bronchus or lung', 'Mortimer Lenormand');
insert into vacuna (id, descripcion_enfermedad, nombre) values (37, 'Unsp injury to unsp level of lumbar spinal cord, init encntr', 'Pepi Gluyas');
insert into vacuna (id, descripcion_enfermedad, nombre) values (38, 'Explosn of bomb placed during war op but expld after, civ', 'Daphne Gotts');
insert into vacuna (id, descripcion_enfermedad, nombre) values (39, 'Sltr-haris Type I physl fx low end ulna, unsp arm, 7thD', 'Marysa Hannond');
insert into vacuna (id, descripcion_enfermedad, nombre) values (40, 'Nondisp Rolando''s fracture, l hand, subs for fx w routn heal', 'Mal Robertsson');
insert into vacuna (id, descripcion_enfermedad, nombre) values (41, 'Passenger injured in collision w oth mv nontraf, subs', 'Wallache Vardy');
insert into vacuna (id, descripcion_enfermedad, nombre) values (42, 'Type 2 diabetes mellitus with circulatory complications', 'Bebe Ridgway');
insert into vacuna (id, descripcion_enfermedad, nombre) values (43, 'Other ulcerative colitis with complications', 'Monah Baress');
insert into vacuna (id, descripcion_enfermedad, nombre) values (44, 'Other disorders of ear, not elsewhere classified', 'Marcelia Cowlam');
insert into vacuna (id, descripcion_enfermedad, nombre) values (45, 'Unspecified injury of tail of pancreas', 'Noella Hilling');
insert into vacuna (id, descripcion_enfermedad, nombre) values (46, 'Complex regional pain syndrome I of unspecified lower limb', 'Merline Cridlon');
insert into vacuna (id, descripcion_enfermedad, nombre) values (47, 'Drug-induced chronic gout, unspecified knee, without tophus', 'Rania Ormond');
insert into vacuna (id, descripcion_enfermedad, nombre) values (48, 'Toxic effect of oth tobacco and nicotine, assault, init', 'Linzy Stonehouse');
insert into vacuna (id, descripcion_enfermedad, nombre) values (49, 'Injury of right uterine vein, sequela', 'Penelope Tunnacliffe');
insert into vacuna (id, descripcion_enfermedad, nombre) values (50, 'Dislocation of proximal interphaln joint of r mid finger', 'Gloriane Domenichelli');
insert into vacuna (id, descripcion_enfermedad, nombre) values (51, 'Ped on rolr-skt inj in clsn w nonmtr vehicle nontraf, init', 'Felic Gilardoni');
insert into vacuna (id, descripcion_enfermedad, nombre) values (52, 'Disord of art, arterioles and capilare in dis classd elswhr', 'Justino MacAnulty');
insert into vacuna (id, descripcion_enfermedad, nombre) values (53, 'Monteggia''s fx unsp ulna, 7thH', 'Sascha Tirone');
insert into vacuna (id, descripcion_enfermedad, nombre) values (54, 'Other specified injury of muscle, fascia and tendon of hip', 'Aldridge Robbe');
insert into vacuna (id, descripcion_enfermedad, nombre) values (55, 'Acquired absence of kidney', 'Sybille Lightning');
insert into vacuna (id, descripcion_enfermedad, nombre) values (56, 'Prsn brd/alit a 3-whl mv injured in clsn w statnry object', 'Kristan Greenrodd');
insert into vacuna (id, descripcion_enfermedad, nombre) values (57, 'Unspecified fall due to ice and snow', 'Anderson Causnett');
insert into vacuna (id, descripcion_enfermedad, nombre) values (58, 'Disp fx of head of unsp rad, 7thN', 'Brien Gasparro');
insert into vacuna (id, descripcion_enfermedad, nombre) values (59, 'Other specified injury of blood vessel of right index finger', 'Yvette Simakov');
insert into vacuna (id, descripcion_enfermedad, nombre) values (60, 'Toxic effect of herbicides and fungicides, assault, init', 'Etan Currum');
insert into vacuna (id, descripcion_enfermedad, nombre) values (61, 'Benign neoplasm of nasopharynx', 'Robert O''Cannon');
insert into vacuna (id, descripcion_enfermedad, nombre) values (62, 'Anterior dislocation of unsp ulnohumeral joint, sequela', 'Jarrad Yallop');
insert into vacuna (id, descripcion_enfermedad, nombre) values (63, 'Embolism and thrombosis of vena cava and oth thoracic veins', 'Cammi Cometti');
insert into vacuna (id, descripcion_enfermedad, nombre) values (64, 'Unsp mtrcy rider injured in clsn w pedl cyc in traf, init', 'Clementia Dulanty');
insert into vacuna (id, descripcion_enfermedad, nombre) values (65, 'Pnctr w/o foreign body of unsp toe(s) w/o damage to nail', 'Zach Shipsey');
insert into vacuna (id, descripcion_enfermedad, nombre) values (66, 'Torus fracture of lower end of unspecified radius, sequela', 'Izabel Wodham');
insert into vacuna (id, descripcion_enfermedad, nombre) values (67, 'Bennett''s fracture, right hand, subs for fx w delay heal', 'Toinette Pile');
insert into vacuna (id, descripcion_enfermedad, nombre) values (68, 'Unsp disseminated chorioretinal inflammation, left eye', 'Cyndy Brahan');
insert into vacuna (id, descripcion_enfermedad, nombre) values (69, 'Injury of unsp muscle, fascia and tendon at shldr/up arm', 'Olwen Canadine');
insert into vacuna (id, descripcion_enfermedad, nombre) values (70, 'Pedestrian injured in traf involving unsp mv, subs', 'Marjorie Maciaszek');
insert into vacuna (id, descripcion_enfermedad, nombre) values (71, 'Otitis media, unspecified', 'Fidole Whitman');
insert into vacuna (id, descripcion_enfermedad, nombre) values (72, 'Chlamydial female pelvic inflammatory disease', 'Phaedra Fehner');
insert into vacuna (id, descripcion_enfermedad, nombre) values (73, 'Partial traumatic amputation of right foot, level unsp, subs', 'Marj Tarburn');
insert into vacuna (id, descripcion_enfermedad, nombre) values (74, 'Occup of pk-up/van injured in clsn w oth and unsp mv nontraf', 'Lezley Horley');
insert into vacuna (id, descripcion_enfermedad, nombre) values (75, 'Oth psychoactive substance dependence w intox delirium', 'Martie Mundow');
insert into vacuna (id, descripcion_enfermedad, nombre) values (76, 'Puncture wound with foreign body, unspecified knee, sequela', 'Filbert Glasspool');
insert into vacuna (id, descripcion_enfermedad, nombre) values (77, 'Vis def/sptl nglct following cerebral infarction', 'Klarrisa Nowill');
insert into vacuna (id, descripcion_enfermedad, nombre) values (78, 'Kaschin-Beck disease, multiple sites', 'Ennis Oleksinski');
insert into vacuna (id, descripcion_enfermedad, nombre) values (79, 'Other fracture of occiput, unspecified side, init', 'Tallulah Kharchinski');
insert into vacuna (id, descripcion_enfermedad, nombre) values (80, 'Other accident with wheelchair (powered), sequela', 'Olin Tuffey');
insert into vacuna (id, descripcion_enfermedad, nombre) values (81, 'Burn due to localized fire on board sailboat, subs encntr', 'Veda Salerno');
insert into vacuna (id, descripcion_enfermedad, nombre) values (82, 'Poisoning by unsp drug/meds/biol subst, self-harm, subs', 'Tarrance Gawke');
insert into vacuna (id, descripcion_enfermedad, nombre) values (83, 'Unspecified juvenile rheumatoid arthritis, ankle and foot', 'Rani Dix');
insert into vacuna (id, descripcion_enfermedad, nombre) values (84, 'Activity, water skiing and wake boarding', 'Hobard Camplejohn');
insert into vacuna (id, descripcion_enfermedad, nombre) values (85, 'Thyrotoxicosis factitia', 'Erinna Snelson');
insert into vacuna (id, descripcion_enfermedad, nombre) values (86, 'Inj extn musc/fasc/tend r rng fngr at wrs/hnd lv, sequela', 'Percy Gerok');
insert into vacuna (id, descripcion_enfermedad, nombre) values (87, 'Oth fracture of shaft of radius, right arm, init for clos fx', 'Geordie Currm');
insert into vacuna (id, descripcion_enfermedad, nombre) values (88, 'Fracture of ramus of right mandible, 7thD', 'Linn Eliaz');
insert into vacuna (id, descripcion_enfermedad, nombre) values (89, 'Partial traumatic transphalangeal amputation of thmb, subs', 'Dorolisa Kubiczek');
insert into vacuna (id, descripcion_enfermedad, nombre) values (90, 'Weeks of gestation of pregnancy not specified', 'Elijah Lockyer');
insert into vacuna (id, descripcion_enfermedad, nombre) values (91, 'Other specified injuries of larynx, initial encounter', 'Celeste Yurlov');
insert into vacuna (id, descripcion_enfermedad, nombre) values (92, 'Kaposi''s sarcoma of gastrointestinal sites', 'Turner Musgrove');
insert into vacuna (id, descripcion_enfermedad, nombre) values (93, 'Malignant neoplasm of broad ligament', 'Averil MacGuffog');
insert into vacuna (id, descripcion_enfermedad, nombre) values (94, 'Other disorders of branched-chain amino-acid metabolism', 'Therine Stark');
insert into vacuna (id, descripcion_enfermedad, nombre) values (95, 'Adverse effect of drug/meds/biol subst, sequela', 'Libbi Beeze');
insert into vacuna (id, descripcion_enfermedad, nombre) values (96, 'Corrosion of unsp degree of left shoulder, subs encntr', 'Anders Cater');
insert into vacuna (id, descripcion_enfermedad, nombre) values (97, 'Oth fracture of shaft of unsp ulna, init for opn fx type I/2', 'Matilde Duplock');
insert into vacuna (id, descripcion_enfermedad, nombre) values (98, 'Complete traumatic amputation of right midfoot, init encntr', 'Lilah Caton');
insert into vacuna (id, descripcion_enfermedad, nombre) values (99, 'Pasngr in 3-whl mv injured in clsn w ped/anml in traf, init', 'Elvina Beine');
insert into vacuna (id, descripcion_enfermedad, nombre) values (100, 'Toxic effect of tin and its compounds, accidental', 'Gawen Massen');